apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo=project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-project
  template:
    metadata:
      labels:
        app: demo-project
    spec:
      containers:
      - name: demo-container
        image: sharmila445/demo-pullingcode
         imagePullPolicy: Always
        ports:
        - containerPort: 80
